### ISSUE TITLE
LAPACKException(1) in nullspace

### ISSUE THREAD

**Issue by MGYamada** [maartenvd/SUNRepresentations.jl#3]
It seems that nullspace sometimes fails with  LinearAlgebra.LAPACKException(1).
This can be reproduced for example by `CGC(Irrep((7, 3, 1, 0)), Irrep((7, 6, 4, 0)), Irrep((0, 0, 0, 0)))` in my environment.

I suggest using SPQR instead of svd-based nullspace.

**Comment by maartenvd** [comment]
I have also noticed this, locally I now use an svd-based nullspace but with gesvd instead of gesdd. This is slower but doesn't fail. 

I have no experience with spqr - in principle we only use nullspace() on a dense matrix. I can try it out, but can you test again with the latest master?

**Comment by MGYamada** [comment]
Thank you very much. The latest master version works fine for me!
